##### Numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
list_of_lists=([[2,5,6,2],[5,9,10,4],[11,31,40,19],[10,20,30,40]])
list_of_lists

[[2, 5, 6, 2], [5, 9, 10, 4], [11, 31, 40, 19], [10, 20, 30, 40]]

In [5]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np.arange(1,99)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(2,20,10)

array([ 2, 12])

In [10]:
np.arange(4,50,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [11]:
np.arange(6,200,7)

array([  6,  13,  20,  27,  34,  41,  48,  55,  62,  69,  76,  83,  90,
        97, 104, 111, 118, 125, 132, 139, 146, 153, 160, 167, 174, 181,
       188, 195])

In [12]:
np.zeros(16)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros(11,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(13,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(1,30,5)

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [21]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [22]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [23]:
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [24]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
np.random.rand(2,5)

array([[0.63811574, 0.53992383, 0.40108837, 0.92222021, 0.90232248],
       [0.34368652, 0.06619422, 0.53060944, 0.20368042, 0.15092449]])

In [26]:
np.random.randn(2,5)

array([[-0.16227419,  0.69389563, -0.61065349,  0.15594038,  0.86075948],
       [-1.24497001, -0.50625292, -0.19314344,  0.52412597, -0.58503401]])

In [29]:
np.random.randint(1,10)

8

In [30]:
np.random.randint(2,30,100)

array([25,  5, 13,  4, 25, 10, 21, 13,  4, 12,  7, 23, 12,  7,  5, 11, 21,
       17, 11,  7,  9, 11, 27, 18,  5, 23,  8, 12,  2, 14, 25, 24, 19, 17,
        8, 23, 23, 25, 10, 23, 27,  3, 20, 21, 14, 19,  5,  2, 14, 29,  7,
       13,  7, 20, 22, 17,  3,  5, 22,  9,  5, 20, 27, 23, 20, 19, 25, 11,
       14, 25, 16,  4, 14, 13, 26,  5, 27, 29, 24,  6, 14, 29, 24,  2, 16,
        7, 18, 14, 11, 28, 13, 14, 23, 23, 18, 16, 15, 20, 26, 28])

In [31]:
np.random.randint(10,1)

ValueError: low >= high

In [34]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
sample_array=np.arange(4,49)
sample_array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [42]:
sample_array=np.arange(30)

In [43]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
rand_array=np.random.randint(0,100,20)
rand_array

array([56, 49, 62, 10, 20, 49, 83, 27, 60, 46, 66, 56, 38,  4, 50, 50, 40,
       65, 26, 40])

In [45]:
rand_array.min()

4

In [46]:
rand_array.max()

83

In [49]:
rand_array.argmax()

6

In [51]:
a=np.random.rand(2,3)
a

array([[0.92466913, 0.62939153, 0.81258734],
       [0.68581135, 0.54297791, 0.76259657]])

In [54]:
sample_array=np.arange(12,21)
sample_array

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[0]

12

In [58]:
sample_array[8]

20

In [59]:
sample_array[2:5]

array([14, 15, 16])

In [61]:
sample_matrix=np.array(([2,3,4],[5,6,7],[8,9,10]))
sample_matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [62]:
sample_matrix[2][2]

10

In [63]:
sample_matrix[1][2]

7

In [64]:
sample_matrix[2]

array([ 8,  9, 10])

In [65]:
sample_matrix[0][1]

3

In [69]:
sample_matrix[1,:]

array([5, 6, 7])

In [71]:
sample_matrix[1:]

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [72]:
sample_matrix[:1]

array([[2, 3, 4]])

In [73]:
sample_matrix[2,1:3]

array([ 9, 10])

In [75]:
sample_matrix[1,2]

7

In [77]:
sample_matrix[1:3,2]

array([ 7, 10])

In [78]:
sample_array

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [79]:
sample_array+sample_array

array([24, 26, 28, 30, 32, 34, 36, 38, 40])

In [80]:
np.log(sample_array)

array([2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
       2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [81]:
np.min(sample_array)

12

In [82]:
np.max(sample_array)

20

In [83]:
np.sqrt(sample_array)

array([3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [84]:
np.argmin(sample_array)

0

In [85]:
np.mean(sample_array)

16.0

In [86]:
np.var(sample_array)

6.666666666666667

In [87]:
np.std(sample_array)

2.581988897471611

In [90]:
array=np.random.randn(3,6)
array

array([[-0.04591948, -1.14170444,  0.45813871, -0.76741402,  0.60297049,
         0.29720637],
       [-0.24160633, -0.27740483,  0.76891072,  0.85722946,  1.42549722,
        -0.30289235],
       [ 0.99141454, -1.39500524,  0.32628916, -0.10532557, -0.06530073,
        -0.42183842]])

In [91]:
np.round(array,decimals=2)

array([[-0.05, -1.14,  0.46, -0.77,  0.6 ,  0.3 ],
       [-0.24, -0.28,  0.77,  0.86,  1.43, -0.3 ],
       [ 0.99, -1.4 ,  0.33, -0.11, -0.07, -0.42]])

In [92]:
sports=np.array(['golf','football','cricket','golf','basketball','vollyball','vollyball'])
np.unique(sports)

array(['basketball', 'cricket', 'football', 'golf', 'vollyball'],
      dtype='<U10')